-- CatchPapers account data. Run once in the Supabase SQL editor.
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  interests text not null default '' check (char_length(interests) <= 12000),
  excluded text not null default '' check (char_length(excluded) <= 3000),
  favorite_journal_ids text[] not null default '{}',
  saved_paper_ids text[] not null default '{}',
  alert_frequency text not null default 'daily' check (alert_frequency in ('daily', 'weekly')),
  alerts_enabled boolean not null default true,
  unsubscribe_token uuid not null default gen_random_uuid(),
  last_alert_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_unsubscribe_token_idx on public.profiles(unsubscribe_token);

create table if not exists public.alert_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  paper_key text not null,
  paper_title text not null,
  delivered_at timestamptz not null default now(),
  unique (user_id, paper_key)
);

alter table public.profiles enable row level security;
alter table public.alert_deliveries enable row level security;

drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile" on public.profiles for select
  to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users insert own profile" on public.profiles;
create policy "Users insert own profile" on public.profiles for insert
  to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update
  to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users read own deliveries" on public.alert_deliveries;
create policy "Users read own deliveries" on public.alert_deliveries for select
  to authenticated using ((select auth.uid()) = user_id);

create or replace function public.set_profile_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_profile_updated_at();

-- Lets an authenticated user permanently delete their own account.
create or replace function public.delete_own_account()
returns void language plpgsql security definer set search_path = '' as $$
begin
  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.delete_own_account() from public;
grant execute on function public.delete_own_account() to authenticated;

-- A random bearer token in each email lets recipients pause alerts without signing in.
create or replace function public.unsubscribe_alerts(token uuid)
returns void language sql security definer set search_path = '' as $$
  update public.profiles set alerts_enabled = false where unsubscribe_token = token;
$$;

revoke all on function public.unsubscribe_alerts(uuid) from public;
grant execute on function public.unsubscribe_alerts(uuid) to anon, authenticated;
